"""dropped SidewalkSegment table for SidewalkSegment2

Revision ID: 0a7e686eeb18
Revises: 551596122117
Create Date: 2020-03-01 10:42:18.312286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0a7e686eeb18'
down_revision = '551596122117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidewalk_segment2',
    sa.Column('segmentId', sa.Integer(), nullable=False),
    sa.Column('directionInd', sa.String(length=50), nullable=False),
    sa.Column('linearId', sa.Integer(), nullable=False),
    sa.Column('streetName', sa.Text(), nullable=True),
    sa.Column('startLat', sa.Float(), nullable=False),
    sa.Column('startLong', sa.Float(), nullable=False),
    sa.Column('endLat', sa.Float(), nullable=False),
    sa.Column('endLong', sa.Float(), nullable=False),
    sa.Column('geoJson', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('segmentId', 'directionInd')
    )
    op.drop_table('sidewalk_segment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidewalk_segment',
    sa.Column('linearId', sa.INTEGER(), nullable=False),
    sa.Column('directionInd', sa.VARCHAR(length=50), nullable=False),
    sa.Column('streetName', sa.TEXT(), nullable=True),
    sa.Column('startLat', sa.FLOAT(), nullable=False),
    sa.Column('startLong', sa.FLOAT(), nullable=False),
    sa.Column('endLat', sa.FLOAT(), nullable=False),
    sa.Column('endLong', sa.FLOAT(), nullable=False),
    sa.Column('geoJson', sqlite.JSON(), nullable=False),
    sa.Column('segmentId', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('linearId', 'directionInd')
    )
    op.drop_table('sidewalk_segment2')
    # ### end Alembic commands ###
