"""retrying this without the pano foreign key situation

Revision ID: 1c7c1370671a
Revises: 3806c54926a7
Create Date: 2020-03-02 21:45:29.884530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c7c1370671a'
down_revision = '3806c54926a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_to_pano2',
    sa.Column('linkId', sa.Integer(), nullable=False),
    sa.Column('segmentId', sa.Integer(), nullable=True),
    sa.Column('panoId', sa.Integer(), nullable=True),
    sa.Column('headingDegree', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['segmentId'], ['sidewalk_segment2.segmentId'], ),
    sa.PrimaryKeyConstraint('linkId')
    )
    op.drop_table('segment_to_pano')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_to_pano',
    sa.Column('linkId', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('segmentId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('panoId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('headingDegree', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['segmentId'], ['sidewalk_segment2.segmentId'], name='segment_to_pano_ibfk_1'),
    sa.PrimaryKeyConstraint('linkId'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('segment_to_pano2')
    # ### end Alembic commands ###
