"""point feature table

Revision ID: 310940cbb5fa
Revises: fac791eae87d
Create Date: 2020-02-29 09:56:27.412449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310940cbb5fa'
down_revision = 'fac791eae87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panoId', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('roadId', sa.Integer(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('point_feature')
    # ### end Alembic commands ###
