"""added segmentId as new PK to SidewalkSegment table

Revision ID: 551596122117
Revises: 77201a9a3f51
Create Date: 2020-03-01 10:34:36.095847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551596122117'
down_revision = '77201a9a3f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sidewalk_segment', sa.Column('segmentId', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sidewalk_segment', 'segmentId')
    # ### end Alembic commands ###
