"""start from scratch

Revision ID: 77201a9a3f51
Revises:
Create Date: 2020-02-29 19:22:04.912154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77201a9a3f51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pano',
    sa.Column('panoId', sa.String(length=50), nullable=False),
    sa.Column('headingDegree', sa.Float(), nullable=False),
    sa.Column('linearId', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('panoId', 'headingDegree')
    )
    op.create_table('pano_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panoId', sa.String(length=50), nullable=True),
    sa.Column('linearId', sa.Integer(), nullable=False),
    sa.Column('headingDegree', sa.Float(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sidewalk_segment',
    sa.Column('linearId', sa.Integer(), nullable=False),
    sa.Column('directionInd', sa.String(length=50), nullable=False),
    sa.Column('streetName', sa.Text(), nullable=True),
    sa.Column('startLat', sa.Float(), nullable=False),
    sa.Column('startLong', sa.Float(), nullable=False),
    sa.Column('endLat', sa.Float(), nullable=False),
    sa.Column('endLong', sa.Float(), nullable=False),
    sa.Column('geoJson', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('linearId', 'directionInd')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sidewalk_segment')
    op.drop_table('pano_feature')
    op.drop_table('pano')
    # ### end Alembic commands ###
