"""reorg of tables

Revision ID: a35d036607f3
Revises: 310940cbb5fa
Create Date: 2020-02-29 17:29:49.079621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35d036607f3'
down_revision = '310940cbb5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pano',
    sa.Column('panoId', sa.Text(), nullable=False),
    sa.Column('headingDegree', sa.Float(), nullable=False),
    sa.Column('linearId', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('panoId', 'headingDegree')
    )
    op.create_table('pano_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panoId', sa.Text(), nullable=False),
    sa.Column('linearId', sa.Integer(), nullable=False),
    sa.Column('headingDegree', sa.Float(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sidewalk_segment',
    sa.Column('linearId', sa.Integer(), nullable=False),
    sa.Column('directionInd', sa.Text(), nullable=False),
    sa.Column('streetName', sa.Text(), nullable=True),
    sa.Column('startLat', sa.Float(), nullable=False),
    sa.Column('startLong', sa.Float(), nullable=False),
    sa.Column('endLat', sa.Float(), nullable=False),
    sa.Column('endLong', sa.Float(), nullable=False),
    sa.Column('geoJson', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('linearId', 'directionInd')
    )
    op.drop_table('point_feature')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_feature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('panoId', sa.TEXT(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('long', sa.FLOAT(), nullable=False),
    sa.Column('roadId', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sidewalk_segment')
    op.drop_table('pano_feature')
    op.drop_table('pano')
    # ### end Alembic commands ###
