"""added sidewalksegment4 as clone of sidewalksegment3

Revision ID: bb0fcfe94129
Revises: 2231bf24b681
Create Date: 2020-03-29 12:42:26.732452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0fcfe94129'
down_revision = '2231bf24b681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidewalk_segment4',
    sa.Column('segmentId', sa.Integer(), nullable=False),
    sa.Column('directionInd', sa.String(length=50), nullable=False),
    sa.Column('roadObjectId', sa.Integer(), nullable=False),
    sa.Column('streetName', sa.Text(), nullable=True),
    sa.Column('startLat', sa.Float(), nullable=False),
    sa.Column('startLong', sa.Float(), nullable=False),
    sa.Column('endLat', sa.Float(), nullable=False),
    sa.Column('endLong', sa.Float(), nullable=False),
    sa.Column('whichArcgisFile', sa.String(length=10), nullable=True),
    sa.Column('roadGrade', sa.Float(), nullable=False),
    sa.Column('geoJson', sa.JSON(), nullable=False),
    sa.Column('updateTs', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('segmentId', 'directionInd')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sidewalk_segment4')
    # ### end Alembic commands ###
