"""update sidewalk_to_pano2 to have sidewalksegment3 as fk instead of ss2

Revision ID: bd0b4477ae02
Revises: fc911e920cfd
Create Date: 2020-03-15 19:34:25.041150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd0b4477ae02'
down_revision = 'fc911e920cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('segment_to_pano2_ibfk_1', 'segment_to_pano2', type_='foreignkey')
    op.create_foreign_key(None, 'segment_to_pano2', 'sidewalk_segment3', ['segmentId'], ['segmentId'])
    op.add_column('sidewalk_segment3', sa.Column('roadObjectId', sa.Integer(), nullable=False))
    op.drop_column('sidewalk_segment3', 'linearId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sidewalk_segment3', sa.Column('linearId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('sidewalk_segment3', 'roadObjectId')
    op.drop_constraint(None, 'segment_to_pano2', type_='foreignkey')
    op.create_foreign_key('segment_to_pano2_ibfk_1', 'segment_to_pano2', 'sidewalk_segment2', ['segmentId'], ['segmentId'])
    # ### end Alembic commands ###
