"""updates to sidewalksegment3

Revision ID: fc911e920cfd
Revises: 1c7c1370671a
Create Date: 2020-03-15 15:07:21.329760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc911e920cfd'
down_revision = '1c7c1370671a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sidewalk_segment3',
    sa.Column('segmentId', sa.Integer(), nullable=False),
    sa.Column('directionInd', sa.String(length=50), nullable=False),
    sa.Column('linearId', sa.Integer(), nullable=False),
    sa.Column('streetName', sa.Text(), nullable=True),
    sa.Column('startLat', sa.Float(), nullable=False),
    sa.Column('startLong', sa.Float(), nullable=False),
    sa.Column('endLat', sa.Float(), nullable=False),
    sa.Column('endLong', sa.Float(), nullable=False),
    sa.Column('whichArcgisFile', sa.String(length=10), nullable=True),
    sa.Column('roadGrade', sa.Float(), nullable=False),
    sa.Column('geoJson', sa.JSON(), nullable=False),
    sa.Column('updateTs', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('segmentId', 'directionInd')
    )
    op.drop_table('static_json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_json',
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('json', mysql.JSON(), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('sidewalk_segment3')
    # ### end Alembic commands ###
